### PR TITLE
fix: match libp2p/interface-peer-discovery spec

### LINKED ISSUE #44: randomWalk should be tested through interface-peer-discovery tests
The current `randomWalk` implementation is not being tested with the [libp2p/interface-peer-discovery](https://github.com/libp2p/interface-peer-discovery).

This should have a similar implementation suite of tests like the other `peer-discovery` modules.

### PR DESCRIPTION
**Pull request by andycodesstuff**
The following pull requests fixes #44 and #111 by matching the `libp2p/interface-peer-discovery` spec.

### CODE REVIEW

**Comment by andrycodestuffs** [comment]
Hope to finish this as soon as possible, I'll keep you updated!

**Comment by vasco-santos** [comment]
Cool, really glad that you are taking this. Bear in mind that we are also working on moving from callback into Promises, which may reflect on this: [ipfs/js-ipfs#1670](https://github.com/ipfs/js-ipfs/issues/1670)

**Comment by andrycodestuffs** [comment]
@vasco-santos could you please provide a very small example of how is random walk discovery implemented at the moment?
I'd like to have a reference point to understand the current execution flow

**Comment by vasco-santos** [comment]
At the moment, random-walk is started and stopped within the `DHT` codebase, if it is enabled through the received options:

https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/index.js#L170
https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/index.js#L184

Briefly, the `random-walk` receives the `dht` instance (https://github.com/libp2p/js-libp2p-kad-dht/blob/master/src/index.js#L136) and uses it to create queries in the DHT. 

When a peer is found via those queries, a event is fired https://github.com/libp2p/js-libp2p-kad-dht/blob/30fd44a5780e6ca9bad3387478c0643a27ecce3b/src/index.js#L699 with the discovered peer, which should be inside the `random-walk` scope. 

As a result, we should be able to change the configuration to use it separately. Taking an example on the `libp2p` configuration in `js-ipfs` (https://github.com/ipfs/js-ipfs/blob/master/src/core/runtime/libp2p-nodejs.js#L43-L48), we should be able to add a random-walk instance inside `peerDiscovery`. Some stuff needs to change in the configuration side of things too, as we need to create the DHT instance in advance, in order to create the `random-walk`.

Also note that the `random-walk` needs to be exported to be used in the `js-libp2p` scope

**Comment by achingbrain** [comment]
Thanks for taking the time to open this, I'm sorry it never landed.  Random walk has been removed from the implementation as it can make queries now instead.

**Pull request closed without merging**
