### PR TITLE
feat: tag kad-close peers

### PR DESCRIPTION
**Pull request by achingbrain**
When peers are added or removed from the kbuckets, if the `kBucketSize` closest peers change, update their peer store tags to ensure we don't close connections to them when the connection manager reaches it's max connections limit.

### CODE REVIEW

**Review by mpetrunic — APPROVED** [review]
LGTM, @wemeetagain  do you also wanna review this?

**Comment by achingbrain** [comment]
I thinking maybe we want to tag them with `keep-alive` too, this will mean we try to reconnect on node startup.

**Comment by mpetrunic** [comment]
> I thinking maybe we want to tag them with `keep-alive` too, this will mean we try to reconnect on node startup.

I was contemplating the same but I feel like it's better if we tag them differently, on startup or pruning we can determine priorities. Like we could prune 'kad-close' tags before 'keep-alive' tags or something.

Or did you mean putting two tags?

**Comment by achingbrain** [comment]
I was thinking `keep-alive` in addition to `kad-close`.

**Pull request merged**
